// AUTO-GENERATED by /generate-react — do not edit manually.
// @ts-nocheck

import * as accordionComp from "@/components/ui/accordion";
import * as alertComp from "@/components/ui/alert";
import * as avatarComp from "@/components/ui/avatar";
import * as badgeComp from "@/components/ui/badge";
import * as boxComp from "@/components/ui/box";
import * as breadcrumbComp from "@/components/ui/breadcrumb";
import * as buttonComp from "@/components/ui/button";
import * as carouselComp from "@/components/ui/carousel";
import * as chartComp from "@/components/ui/chart";
import * as checkboxComp from "@/components/ui/checkbox";
import * as comboboxComp from "@/components/ui/combobox";
import * as datepickerComp from "@/components/ui/datepicker";
import * as dialogComp from "@/components/ui/dialog";
import * as fieldComp from "@/components/ui/field";
import * as fileIconComp from "@/components/ui/file-icon";
import * as inputComp from "@/components/ui/input";
import * as labelComp from "@/components/ui/label";
import * as mapComp from "@/components/ui/map";
import * as menuComp from "@/components/ui/menu";
import * as nativeSelectComp from "@/components/ui/native-select";
import * as paginationComp from "@/components/ui/pagination";
import * as popoverComp from "@/components/ui/popover";
import * as progressCircularComp from "@/components/ui/progress-circular";
import * as progressLinearComp from "@/components/ui/progress-linear";
import * as radioGroupComp from "@/components/ui/radio-group";
import * as scrollAreaComp from "@/components/ui/scroll-area";
import * as selectComp from "@/components/ui/select";
import * as sheetComp from "@/components/ui/sheet";
import * as sliderComp from "@/components/ui/slider";
import * as switchComp from "@/components/ui/switch";
import * as tableComp from "@/components/ui/table";
import * as tabsComp from "@/components/ui/tabs";
import * as textareaComp from "@/components/ui/textarea";
import * as toastComp from "@/components/ui/toast";
import * as tooltipComp from "@/components/ui/tooltip";
import * as lucide from "lucide-react";
import { ArrowUpDown, MoreVertical } from "lucide-react";
import React, { useState, useEffect, useRef, useCallback, useMemo, useId, useReducer } from "react";
import { CheckboxRoot, CheckboxControl } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { MenuRoot, MenuTrigger, MenuPositioner, MenuContent, MenuItem } from "@/components/ui/menu";
import { flexRender, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from "@tanstack/react-table";

// ─── Demo data extracted from pages ──────────────────────────────────────────

// from carousel.tsx
const images = Array.from(
  { length: 5 },
  (_, i) => `https://picsum.photos/seed/${i + 1}/500/300`
);

// from combobox.tsx
// Extracted from Main body
const stateSingle = ["React"];
const setStateSingle = (..._args: unknown[]) => {};
const stateMultiple = [] as unknown[];
const setStateMultiple = (..._args: unknown[]) => {};
const stateTimezone = [] as unknown[];
const setStateTimezone = (..._args: unknown[]) => {};

// from data-table.tsx
const data: Payment[] = [
  {
    id: "m5gr84i9",
    amount: 316,
    status: "success",
    badge: "success",
    email: "ken99@example.com",
  },
  {
    id: "3u1reuv4",
    amount: 242,
    status: "success",
    badge: "success",
    email: "Abe45@example.com",
  },
  {
    id: "derv1ws0",
    amount: 837,
    status: "processing",
    badge: "pending",
    email: "Monserrat44@example.com",
  },
  {
    id: "5kma53ae",
    amount: 874,
    status: "success",
    badge: "success",
    email: "Silas22@example.com",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    badge: "danger",
    email: "carmella@example.com",
  },
];

const columns: ColumnDef<Payment>[] = [
  {
    id: "select",
    header: ({ table }) => (
      <CheckboxRoot
        checked={
          table.getIsAllPageRowsSelected() ||
          (table.getIsSomePageRowsSelected() && "indeterminate")
        }
        onCheckedChange={(details) =>
          table.toggleAllPageRowsSelected(!!details.checked)
        }
      >
        <CheckboxControl aria-label="Select all" />
      </CheckboxRoot>
    ),
    cell: ({ row }) => (
      <CheckboxRoot
        checked={row.getIsSelected()}
        onCheckedChange={(details) => row.toggleSelected(!!details.checked)}
      >
        <CheckboxControl aria-label="Select row" />
      </CheckboxRoot>
    ),
    enableSorting: false,
    enableHiding: false,
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => (
      <Badge variant={row.original.badge} className="capitalize">
        {row.getValue("status")}
      </Badge>
    ),
  },
  {
    accessorKey: "email",
    header: ({ column }) => {
      return (
        <div
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="flex gap-2 items-center cursor-pointer"
        >
          Email
          <ArrowUpDown className="size-3" />
        </div>
      );
    },
    cell: ({ row }) => <div className="lowercase">{row.getValue("email")}</div>,
  },
  {
    accessorKey: "amount",
    header: () => <div className="text-right">Amount</div>,
    cell: ({ row }) => {
      const amount = parseFloat(row.getValue("amount"));
      const formatted = new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
      }).format(amount);
      return <div className="text-right font-medium">{formatted}</div>;
    },
  },
  {
    id: "actions",
    enableHiding: false,
    header: () => <div className="text-center">Actions</div>,
    cell: ({ row }) => {
      const payment = row.original;
      return (
        <MenuRoot>
          <MenuTrigger asChild>
            <div className="cursor-pointer flex justify-center">
              <span className="sr-only">Open menu</span>
              <MoreVertical className="size-4 opacity-70" />
            </div>
          </MenuTrigger>
          <MenuPositioner>
            <MenuContent>
              <MenuItem
                value="copy"
                onClick={() => navigator.clipboard.writeText(payment.id)}
              >
                Copy payment ID
              </MenuItem>
              <MenuItem value="view-cust">View Customer</MenuItem>
              <MenuItem value="view-pay">View Payment</MenuItem>
            </MenuContent>
          </MenuPositioner>
        </MenuRoot>
      );
    },
  },
];



// Extracted from Main body
const sorting = [] as unknown[];
const setSorting = (..._args: unknown[]) => {};
const columnFilters = [] as unknown[];
const setColumnFilters = (..._args: unknown[]) => {};
const columnVisibility = {};
const setColumnVisibility = (..._args: unknown[]) => {};
const rowSelection = {};
const setRowSelection = (..._args: unknown[]) => {};

// from dialog.tsx
// Extracted from Main body
const dialog = false;
const setDialog = (..._args: unknown[]) => {};

// from menu.tsx
// Extracted from Main body
const react = false;
const setReact = (..._args: unknown[]) => {};
const solid = false;
const setSolid = (..._args: unknown[]) => {};
const vue = false;
const setVue = (..._args: unknown[]) => {};
const svelte = false;
const setSvelte = (..._args: unknown[]) => {};
const value = "React";
const setValue = (..._args: unknown[]) => {};

// from table.tsx
const invoices: {
  invoice: string;
  paymentStatus: string;
  badge: "success" | "pending" | "danger";
  totalAmount: string;
  paymentMethod: string;
}[] = [
  {
    invoice: "INV001",
    paymentStatus: "Paid",
    badge: "success",
    totalAmount: "$250.00",
    paymentMethod: "Credit Card",
  },
  {
    invoice: "INV002",
    paymentStatus: "Pending",
    badge: "pending",
    totalAmount: "$150.00",
    paymentMethod: "PayPal",
  },
  {
    invoice: "INV003",
    paymentStatus: "Unpaid",
    badge: "danger",
    totalAmount: "$350.00",
    paymentMethod: "Bank Transfer",
  },
  {
    invoice: "INV004",
    paymentStatus: "Paid",
    badge: "success",
    totalAmount: "$450.00",
    paymentMethod: "Credit Card",
  },
  {
    invoice: "INV005",
    paymentStatus: "Paid",
    badge: "success",
    totalAmount: "$550.00",
    paymentMethod: "PayPal",
  },
  {
    invoice: "INV006",
    paymentStatus: "Pending",
    badge: "pending",
    totalAmount: "$200.00",
    paymentMethod: "Bank Transfer",
  },
  {
    invoice: "INV007",
    paymentStatus: "Unpaid",
    badge: "danger",
    totalAmount: "$300.00",
    paymentMethod: "Credit Card",
  },
];

// ─── Scope ────────────────────────────────────────────────────────────────────
const scope: Record<string, unknown> = {
  React,
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo,
  useId,
  useReducer,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
  // demo data
  images,
  stateSingle,
  setStateSingle,
  stateMultiple,
  setStateMultiple,
  stateTimezone,
  setStateTimezone,
  data,
  columns,
  sorting,
  setSorting,
  columnFilters,
  setColumnFilters,
  columnVisibility,
  setColumnVisibility,
  rowSelection,
  setRowSelection,
  dialog,
  setDialog,
  react,
  setReact,
  solid,
  setSolid,
  vue,
  setVue,
  svelte,
  setSvelte,
  value,
  setValue,
  invoices,
  // lucide first so UI components override any name clash (Box, Badge, Table, Map...)
  ...lucide,
  ...accordionComp,
  ...alertComp,
  ...avatarComp,
  ...badgeComp,
  ...boxComp,
  ...breadcrumbComp,
  ...buttonComp,
  ...carouselComp,
  ...chartComp,
  ...checkboxComp,
  ...comboboxComp,
  ...datepickerComp,
  ...dialogComp,
  ...fieldComp,
  ...fileIconComp,
  ...inputComp,
  ...labelComp,
  ...mapComp,
  ...menuComp,
  ...nativeSelectComp,
  ...paginationComp,
  ...popoverComp,
  ...progressCircularComp,
  ...progressLinearComp,
  ...radioGroupComp,
  ...scrollAreaComp,
  ...selectComp,
  ...sheetComp,
  ...sliderComp,
  ...switchComp,
  ...tableComp,
  ...tabsComp,
  ...textareaComp,
  ...toastComp,
  ...tooltipComp,
};

export default scope;
